### ISSUE TITLE
inconsistency between js and rust implementation's output

### ISSUE THREAD

**Issue by marekyggdrasil** [Ruin0x11/jikyuu#1]
Hey @Ruin0x11 thank you for this great work of re-implementing git-hours in Rust. Very much needed! I was looking forward for a fresh implementation of this great tool.

Today I decided to give it a shot and test a bit and I found something odd. For instance, if we consider the repo https://github.com/grinfans/grinmw.py commit `a08ccdecf0945d3a980c6e2c9495b747f9b7cfc3` and run both of them with same same `--max-commit-diff` numbers I find much different results

jikyuu

```
$ jikyuu -d 120 -f json
[
  {
    "email": "xiaojay@gmail.com",
    "author_name": "xiaojay",
    "hours": 4.2,
    "commit_count": 10
  },
  {
    "email": "bladedoyle@gmail.com",
    "author_name": "Blade Doyle",
    "hours": 1.05,
    "commit_count": 5
  },
  {
    "email": "marek.yggdrasil@gmail.com",
    "author_name": "marekyggdrasil",
    "hours": 0.36666667,
    "commit_count": 4
  },
  {
    "email": "ndcroos@users.noreply.github.com",
    "author_name": "ndcroos",
    "hours": 0.0,
    "commit_count": 1
  },
  {
    "email": null,
    "author_name": "Total",
    "hours": 5.616667,
    "commit_count": 20
  }
]
```

git-hours

```
$ git-hours -d 120
{
  "marek.yggdrasil@gmail.com": {
    "name": "marekyggdrasil",
    "hours": 0,
    "commits": 4
  },
  "ndcroos@users.noreply.github.com": {
    "name": "ndcroos",
    "hours": 0,
    "commits": 1
  },
  "bladedoyle@gmail.com": {
    "name": "Blade Doyle",
    "hours": 4,
    "commits": 5
  },
  "xiaojay@gmail.com": {
    "name": "xiaojay",
    "hours": 18,
    "commits": 14
  },
  "total": {
    "hours": 22,
    "commits": 24
  }
}
```

The total is far off! The Blade Doyle five commits are estimated by jikyuu to take `1.05` hours and according to git-hours they took `4` hours.

Not saying your result is wrong. I think we should estimate which of the implementations is right!

**Comment by Ruin0x11** [comment]
Thanks for letting me know. That makes total sense, but unfortunately because I can't get git-hours to build on my system, I have no real way of verifying the correctness myself (which is the reason I made this project to begin with).

If you or someone else with a working copy of git-hours could provide some known-good data for some Git repositories/commit hashes/sets of options, then I could certainly write some tests to compare the output of each one to jikyuu.

**Comment by marekyggdrasil** [comment]
I totally understand. In my case I am able to install git-hours but I am not able to build it myself, so crazy...

But I offer my help. I will gather some data for you on small repositories.

**Comment by marekyggdrasil** [comment]
@Ruin0x11 are the units ok here? I see you are using seconds

https://github.com/Ruin0x11/jikyuu/blob/16c3bf8aded0b1438ad842308924853265e1b6be/src/main.rs#L385-L395

but in original git-hours its in minutes

https://github.com/kimmobrunfeldt/git-hours/blob/6522059ac11e6802121164f9c67951f9ea8ed82a/src/index.js#L268-L282


maybe that could be the reason?

**Comment by Ruin0x11** [comment]
With chrono's `Duration`, you can represent durations of any time. On this line I convert from minutes to Duration.

https://github.com/Ruin0x11/jikyuu/blob/16c3bf8aded0b1438ad842308924853265e1b6be/src/main.rs#L325

The lines you provided convert the seconds to another Duration. I think they should be using the same units.

**Comment by marekyggdrasil** [comment]
@Ruin0x11 I managed to run both and print different in minutes between consecutive commits in both your implementation and `git-hours` and differences seem to match pretty closely

jikyuu
```
marekyggdrasil
cb6fc90a6c8ad2a745f20fc2fe6088cc363ab275
f3aa6fdeb486a103c08f73257607c19b92c016a9 0
b7b1115034a60a0e5738c921a76ab9aeb683ea4a 1
a08ccdecf0945d3a980c6e2c9495b747f9b7cfc3 20

xiaojay
8e98c1181f7ee8f03499fabea6f9de6848ae7138
d02a08424a2d5ac167c83441967fb706d9de707c 33
22fe03dc39b667103f2eed28318af079abcf3b92 4
fe20b6bf6b191af4f9431aba05b8215da3c20d5e 33052
4b229b228726f78f01213b3a92906f45dd82452b 3
484ffaf02fc3a981f4adf7b95c3a01b97c644b9b 60
7d54baf27d1029d4caa5750367a7a005aa5b7bfc 26512
cc88593530afcfff618ef2a5f52152b578680f2a 33301
c0bd87e7fb9f797e3ba6fd94b68bab56d2bb770c 33129
c7db78d3748965208c6e9aea5562878c407ca13a 42398

Blade Doyle
34b44ca0b954aedd5c4dd84176c4695e615ad19e
9b4694cf2c522d99627a0234aa5a6976268128f7 2
1a5bb96abad86ab92696dabc7828359a8b84e305 577
6d923fdbbc9aab0ec3650b9b871ca1a26fae320e 610
084fd99a88f452cb5e9d53e30bbf45acf0cbaa20 1
```

git-hours
```
marek.yggdrasil@gmail.com
Sun Apr 18 2021 15:06:22 GMT+0800 (CST)
Sun Apr 18 2021 15:06:22 GMT+0800 (CST) 0.26666666666666666
Sun Apr 18 2021 15:06:38 GMT+0800 (CST) 1.6666666666666667
Sun Apr 18 2021 15:08:18 GMT+0800 (CST) 20.1

xiaojay@gmail.com
Wed Dec 16 2020 10:48:18 GMT+0800 (CST)
Wed Dec 16 2020 10:48:18 GMT+0800 (CST) 33.8
Wed Dec 16 2020 11:22:06 GMT+0800 (CST) 4.1
Wed Dec 16 2020 11:26:12 GMT+0800 (CST) 547.5833333333334
Wed Dec 16 2020 20:33:47 GMT+0800 (CST) 1585.1833333333334
Thu Dec 17 2020 22:58:58 GMT+0800 (CST) 30920.066666666666
Fri Jan 08 2021 10:19:02 GMT+0800 (CST) 3.45
Fri Jan 08 2021 10:22:29 GMT+0800 (CST) 60.81666666666667
Fri Jan 08 2021 11:23:18 GMT+0800 (CST) 26512.116666666665
Tue Jan 26 2021 21:15:25 GMT+0800 (CST) 16591.933333333334
Sun Feb 07 2021 09:47:21 GMT+0800 (CST) 16709.366666666665
Fri Feb 19 2021 00:16:43 GMT+0800 (CST) 0.13333333333333333
Fri Feb 19 2021 00:16:51 GMT+0800 (CST) 33129.38333333333
Sun Mar 14 2021 00:26:14 GMT+0800 (CST) 42398.5

ndcroos@users.noreply.github.com

bladedoyle@gmail.com
Wed Dec 16 2020 15:04:17 GMT+0800 (CST)
Wed Dec 16 2020 15:04:17 GMT+0800 (CST) 2.25
Wed Dec 16 2020 15:06:32 GMT+0800 (CST) 577.0333333333333
Thu Dec 17 2020 00:43:34 GMT+0800 (CST) 610.9166666666666
Thu Dec 17 2020 10:54:29 GMT+0800 (CST) 1.5833333333333333
```

and I also figured out how to build git-hours for debugging it, in case if you are interested you need to install [nvm](https://github.com/nvm-sh/nvm) and run the following

```bash
$ git clone git@github.com:kimmobrunfeldt/git-hours.git
$ git checkout b696b68f9c2372b81e695edbfd4b73c1cfbdc992
$ nvm use 5.0
$ nvm install-latest-npm
$ npm install
```

the differences between consecutive commits seem to match, what else could it be...

Edit: actually I did not count the commits, they do not match! git-hours has more commits than jikyuu, maybe merge commits are not taken into account?

**Comment by marekyggdrasil** [comment]
@Ruin0x11 it was that! It was just the merge commits which for git-hours are included by default and in jikyuu need to be included using `-m` option, also to match the default parameters of git-hours we need `-d 120` and `-a 120` and then the results match closely!

jikyuu

```json
$ jikyuu -d 120 -f json -a 120 -m
[
  {
    "email": "xiaojay@gmail.com",
    "author_name": "xiaojay",
    "hours": 17.7,
    "commit_count": 14
  },
  {
    "email": "bladedoyle@gmail.com",
    "author_name": "Blade Doyle",
    "hours": 4.05,
    "commit_count": 5
  },
  {
    "email": "marek.yggdrasil@gmail.com",
    "author_name": "marekyggdrasil",
    "hours": 0.36666667,
    "commit_count": 4
  },
  {
    "email": "ndcroos@users.noreply.github.com",
    "author_name": "ndcroos",
    "hours": 0.0,
    "commit_count": 1
  },
  {
    "email": null,
    "author_name": "Total",
    "hours": 22.116667,
    "commit_count": 24
  }
]

```



git-hours

```json
{
  "marek.yggdrasil@gmail.com": {
    "name": "marekyggdrasil",
    "hours": 0,
    "commits": 4
  },
  "ndcroos@users.noreply.github.com": {
    "name": "ndcroos",
    "hours": 0,
    "commits": 1
  },
  "bladedoyle@gmail.com": {
    "name": "Blade Doyle",
    "hours": 4,
    "commits": 5
  },
  "xiaojay@gmail.com": {
    "name": "xiaojay",
    "hours": 18,
    "commits": 14
  },
  "total": {
    "hours": 22,
    "commits": 24
  }
}
```

many thanks for taking a look!
